name = "Belt"
grammar = "belt"
path_suffixes = ["belt"]
line_comments = ["# "]
tab_size = 2
hard_tabs = false
first_line_pattern = "^#!.*\b(?:belt)\b"
brackets = [
  { start = '(', end = ')', close = true, newline = true, not_in = [
    "string",
  ] },
  { start = '[', end = ']', close = true, newline = true, not_in = [
    "string",
  ] },
  { start = '{', end = '}', close = true, newline = true, not_in = [
    "string",
  ] },
  { start = '"', end = '"', close = true, newline = false, not_in = [
    "string",
  ] },
  { start = "'", end = "'", close = true, newline = false, not_in = [
    "string",
  ] },
]
