id = "belt-lang"
name = "Belt"
grammar = "belt"
description = "Belt script language support"
version = "0.1.0"
schema_version = 1
authors = ["lumiknit <aasr4r4@gmail.com>"]
repository = "https://github.com/lumiknit/tree-sitter-belt"
license = "MIT"

[grammars.belt]
repository = "https://github.com/lumiknit/tree-sitter-belt"
commit = "296a89d1e9ad97d5bd09fa2dc1ed019a6b15f2a9"
